"""Add health conditions and drug allergies fields

Revision ID: c8198302fc1b
Revises: 966e401224d2
Create Date: 2025-05-14 07:43:44.212883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8198302fc1b'
down_revision = '966e401224d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('health_conditions', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('drug_allergies', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('drug_allergies')
        batch_op.drop_column('health_conditions')

    # ### end Alembic commands ###
